export const Types = {
    GET_PROFILE: 'GET_PROFILE',
    RESTORE_TOKEN: 'RESTORE_TOKEN',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    UPDATE_QRCODE: 'UPDATE_QRCODE',
    DELETE_QRCODE: 'DELETE_QRCODE'
}